# Generated by Django 4.0.3 on 2024-08-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pastpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='type',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
