# Generated by Django 4.0.3 on 2025-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pastpaper_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='paper',
            field=models.CharField(choices=[('P1', 'Paper 1'), ('P2', 'Paper 2')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='type',
            field=models.CharField(choices=[('QP', 'Question paper'), ('MS', 'Marking scheme'), ('IN', 'Insert')], max_length=2),
        ),
    ]
